### ISSUE TITLE
Temporal Upscaling

### ISSUE THREAD

**Issue by michaelsakharov** [Pjbomb2/TrueTrace-Pathtracer#8]

**Comment by Pjbomb2** [comment]
?

**Comment by michaelsakharov** [comment]
Oh wait what, I didn't actually hit submit on this, I went to work and forgot about it. Sorry, Anyway what I was gonna say was Temporal Upscaling, I don't think you already have it and it can be quite powerful when done correctly. Lets you render out a full image in 2-3 frames or so instead of 1, yet all 3 frames are still visually useable. Something like: https://www.shadertoy.com/view/3l3XR7.

**Comment by Pjbomb2** [comment]
I do have upscaling, both TAAU and my own upscaler that uses some things from FSR 1.0(used to be heavily temporal but it smeared too much)
